#!/usr/bin/env bash
set -euo pipefail

# Get the required variables
MYDIR="$(dirname "$(readlink -f "$0")")"
. "${MYDIR}/common-vars"

# Check if SSL folder exist, if not create

if [[ ! -d "${SSL_DIR}" ]]; then
        mkdir -p "${SSL_DIR}"
fi

# Check if SSL certificates exist, if not create

if [[ ! -f "${SSL_CERT_PATH}" && ! -f "${SSL_KEY_PATH}" ]]; then
    openssl req -x509 -newkey rsa:4096 -keyout "$SSL_KEY_PATH" -out "$SSL_CERT_PATH" -sha256 -days 3650 -nodes -subj "/CN=$CERT_CN" -addext "subjectAltName=DNS:*,DNS:$CERT_CN"
fi
chown 1000:0 "${SSL_DIR}/ssl.*"
chmod 640 "${SSL_DIR}/ssl.key"


# Backup and modify the scripts/files
# This will backup the original scripts/files and modify them with the ones that support https


# Create backups directory structure is it doesnt exists

if [[ ! -d "${BACKUPS_LEGACY_COMPAT_DIR}" ]]; then
        mkdir -p "${BACKUPS_LEGACY_COMPAT_DIR}"
fi
#if [[ ! -d "${BACKUPS_SERVER_DIR}" ]]; then
#        mkdir -p "${BACKUPS_SERVER_DIR}"
#fi

# Backup and Modify app-proxy: Docker Compose File

if [[ ! -f "${BACKUP_APP_PROXY_DOCKER_COMPOSE_PATH}" ]]; then
  cp -a "${ORIGINAL_APP_PROXY_DOCKER_COMPOSE_PATH}" "${BACKUP_APP_PROXY_DOCKER_COMPOSE_PATH}"
  sed -i "s|${ORIGINAL_APP_PROXY_DOCKER_IMAGE}|${MODDED_APP_PROXY_DOCKER_IMAGE}|g" "${ORIGINAL_APP_PROXY_DOCKER_COMPOSE_PATH}"
  sed -i 's|volumes:|volumes:\n      - "${UMBREL_ROOT}/secrets/ssl:/ssl:ro"|' "${ORIGINAL_APP_PROXY_DOCKER_COMPOSE_PATH}"
fi

# Backup and Modify app-proxy: app.ts File

if [[ ! -f "${BACKUP_APP_TS_PATH}" ]]; then
  cp -a "${ORIGINAL_APP_TS_PATH}" "${BACKUP_APP_TS_PATH}"
  sed -i "s|${ORIGINAL_APP_PROXY_DOCKER_IMAGE}|${MODDED_APP_PROXY_DOCKER_IMAGE}|g" "${ORIGINAL_APP_TS_PATH}"
fi

# Backup and Modify app-auth: Docker Compose File

if [[ ! -f "${BACKUP_APP_AUTH_DOCKER_COMPOSE_PATH}" ]]; then
  cp -a "${ORIGINAL_APP_AUTH_DOCKER_COMPOSE_PATH}" "${BACKUP_APP_AUTH_DOCKER_COMPOSE_PATH}"
  sed -i "s|${ORIGINAL_APP_AUTH_DOCKER_IMAGE}|${MODDED_APP_AUTH_DOCKER_IMAGE}|g" "${ORIGINAL_APP_AUTH_DOCKER_COMPOSE_PATH}"
  sed -i -z 's|volumes:|volumes:\n      - "${UMBREL_DATA_DIR}/secrets/ssl:/ssl:ro"|2' "${ORIGINAL_APP_AUTH_DOCKER_COMPOSE_PATH}"
fi
