version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: sahilph-nginx-proxy-manager_web_1
      APP_PORT: 81
    
  web:
    image: jc21/nginx-proxy-manager:2.11.3@sha256:5bd2aae54ac0b6f4ef6777143ab736baf5366807894a4c7fca7bfa2fbaf1489c
    network_mode: "host"
    hostname: sahilph-nginx-proxy-manager_web_1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/letsencrypt:/etc/letsencrypt

    
